<pre><div class="text_to_html">---
title: "Project Part 2"
author: "DIKSHA BANSAL"
date: "April 5, 2018"
output: html_document
---

# Question 1

```{r}
dataset <- system.file("C:/Users/Diksha Bansal/Documents/GitHub/STAT 123/919report_data.xlsx", package = "readxl")

```

```{r, echo = F}
X919_data <- read_excel(dataset)
summary(X919_data)
```

# Question 2


```{r}
timing_cat <- c("Dawn", "Morning", "Noon", "Afternoon", "Evening", "Night")

# Dawn -> 12:01 am to 4:00 am      0.00069444444444444 to 0.16666666666666667 
# Morning -> 4:01 am to 8:00 am    0.16736111111111111 to 0.33333333333333333
# Noon -> 8:01 am to 12:00 pm      0.33402777777777778 to 0.5
# Afternoon -> 12:01 pm to 4:00 pm 0.50069444444444444 to 0.66666666666666667
# Evening -> 4:01 pm to 8:00 pm    0.66736111111111111 to 0.83333333333333333
# Night -> 8:01 pm to 12:00 am     0.83402777777777778 to 1
 

time_vector <- X919_data$Time
len <- length(time_vector)
char_time <- vector(mode = "character", length = len) # create an empty vector

for(i in 1:len){
  if(time_vector[i] > 0 && time_vector[i] <= 0.16666666666666667){
    char_time[i] = "Dawn"
  } else if(time_vector[i] > 0.16666666666666667 && time_vector[i] <= 0.33333333333333333){
    char_time[i] = "Morning"
  } else if(time_vector[i] > 0.33333333333333333 && time_vector[i] <= 0.5){
    char_time[i] = "Noon"
  } else if(time_vector[i] > 0.5 && time_vector[i] <= 0.66666666666666667){
    char_time[i] = "Afternoon"
  } else if(time_vector[i] > 0.66666666666666667 && time_vector[i] <= 0.83333333333333333){
    char_time[i] = "Evening"
  } else{
    char_time[i] = "Night"
  }
}


char_time

```


```{r}
timing_cat <- c("Dawn", "Morning", "Noon", "Afternoon", "Evening", "Night" )
factor_time <- factor(char_time, ordered = T, levels = timing_cat)
 
summary(factor_time)
```

```{r}

ambulance <- X919_data$`Call initiated to: Ambulance  (911)`
overdosed <- X919_data$Overdose

amb_df <- as.data.frame(ambulance)
amb_df[is.na(amb_df)] <- 0 # replacing na with 0
over_df <- as.data.frame(overdosed)
over_df[is.na(over_df)] <- 0
```
# Since COG has the highest value, it is better. 
</div></pre>